application: wordscrabble
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  upload: favicon\.ico
  static_files: favicon.ico

- url: /static
  static_dir: static

- url: .*
  script: game.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
